### PR TITLE
Removes mustache.js from /lib and comments out the only use of it.

### PR DESCRIPTION
**Pull request by alonsogarciapablo**
`wax.cartodb.js` is including `mustache.js` and we're relying on it in `cartodb.js`, but `cartodb.js` is not using the functionally that involves Mustache so we can remove it.

@javisantana @xavijam PTAL.

Thx

### CODE REVIEW

**Comment by javisantana** [comment]
hey, don't include generated files in the PR

**Comment by alonsogarciapablo** [comment]
@javisantana done!

**Comment by javisantana** [comment]
:es:

**Comment by alonsogarciapablo** [comment]
Making sure this change won't affect cartodb.js.

**Pull request merged**
