### PR TITLE
Check if tile exists

### PR DESCRIPTION
**Pull request by donflopez**
cc/ @alonsogarciapablo

### CODE REVIEW

**Comment by alonsogarciapablo** [comment]
👍

**Comment by alonsogarciapablo** [comment]
Please run `make` before merging (just in case). It will generate some dist files...

**Comment by donflopez** [comment]
I usually do it after the merge, for not pollute the PR, but if you wanna see the changes... I can make it!

**Comment by alonsogarciapablo** [comment]
Ok, that'd work too. Thanks!

**Pull request closed without merging**
